// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting resume improvements based on a job description.
 *
 * - suggestResumeImprovements - A function that takes a resume and job description and suggests improvements.
 * - SuggestResumeImprovementsInput - The input type for the suggestResumeImprovements function.
 * - SuggestResumeImprovementsOutput - The output type for the suggestResumeImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestResumeImprovementsInputSchema = z.object({
  resume: z.string().describe('The text content of the resume.'),
  jobDescription: z.string().describe('The job description to align the resume with.'),
});
export type SuggestResumeImprovementsInput = z.infer<typeof SuggestResumeImprovementsInputSchema>;

const SuggestResumeImprovementsOutputSchema = z.object({
  improvements: z.array(
    z.string().describe('A suggestion to improve the resume to better match the job description.')
  ).describe('A list of suggestions to improve the resume.')
});
export type SuggestResumeImprovementsOutput = z.infer<typeof SuggestResumeImprovementsOutputSchema>;

export async function suggestResumeImprovements(input: SuggestResumeImprovementsInput): Promise<SuggestResumeImprovementsOutput> {
  return suggestResumeImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestResumeImprovementsPrompt',
  input: {schema: SuggestResumeImprovementsInputSchema},
  output: {schema: SuggestResumeImprovementsOutputSchema},
  prompt: `You are an expert career coach. You will receive a resume and a job description.
Your task is to provide specific, actionable suggestions on how to improve the resume to better align with the job requirements outlined in the job description.

Resume:
{{resume}}

Job Description:
{{jobDescription}}

Provide a list of specific improvements that can be made to the resume to better match the job description. Be as specific as possible, and provide context as to why the suggestion will improve the resume's chances of getting an interview.
`, 
});

const suggestResumeImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestResumeImprovementsFlow',
    inputSchema: SuggestResumeImprovementsInputSchema,
    outputSchema: SuggestResumeImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
